/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 16-bře-2026 20:14:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS "Category" CASCADE
;

DROP TABLE IF EXISTS "Comment" CASCADE
;

DROP TABLE IF EXISTS "Listing" CASCADE
;

DROP TABLE IF EXISTS "Message" CASCADE
;

DROP TABLE IF EXISTS "Notification" CASCADE
;

DROP TABLE IF EXISTS "Picture" CASCADE
;

DROP TABLE IF EXISTS "Rating" CASCADE
;

DROP TABLE IF EXISTS "Report" CASCADE
;

DROP TABLE IF EXISTS "Ticket" CASCADE
;

DROP TABLE IF EXISTS "User" CASCADE
;

/* Create Tables */

CREATE TABLE "Category"
(
	"Name" varchar(100) NOT NULL,
	"CategoryID" serial NOT NULL,
	"parentCategory" integer NULL
)
;

CREATE TABLE "Comment"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"Text" text NOT NULL,
	"Updatedat" timestamp without time zone NOT NULL   DEFAULT now(),
	"CommentID" serial NOT NULL,
	author integer NULL,
	"parentComment" integer NULL,
	listing integer NULL
)
;

CREATE TABLE "Listing"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"Description" text NULL,
	"Price" numeric NOT NULL   DEFAULT 0.00,
	"State" listing_state NOT NULL   DEFAULT 'active',
	"Title" varchar(255) NOT NULL,
	"Updatedat" timestamp without time zone NULL   DEFAULT now(),
	"ListingID" serial NOT NULL,
	"belongsTo" integer NULL,
	author integer NULL
)
;

CREATE TABLE "Message"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"Text" text NULL,
	"MessageID" serial NOT NULL,
	sender integer NULL,
	ticket integer NULL
)
;

CREATE TABLE "Notification"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"Link" varchar(255) NULL,
	"Read" boolean NOT NULL   DEFAULT false,
	"Text" varchar(255) NOT NULL,
	"NotificationID" serial NOT NULL,
	recipient integer NULL,
	ticket integer NULL
)
;

CREATE TABLE "Picture"
(
	"Path" varchar(255) NOT NULL,
	"PictureID" serial NOT NULL,
	listing integer NULL
)
;

CREATE TABLE "Rating"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"Rating" integer NOT NULL,
	"RatingID" serial NOT NULL,
	reviewed integer NULL,
	reviewer integer NULL
)
;

CREATE TABLE "Report"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"Text" text NOT NULL,
	"ReportID" serial NOT NULL,
	"reportedListing" integer NULL,
	reporter integer NULL,
	"reportedUser" integer NULL
)
;

CREATE TABLE "Ticket"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"State" ticket_state NOT NULL   DEFAULT 'open',
	"Updatedat" timestamp without time zone NOT NULL   DEFAULT now(),
	"TicketID" serial NOT NULL,
	"subjectListing" integer NULL,
	buyer integer NULL
)
;

CREATE TABLE "User"
(
	"Createdat" timestamp without time zone NOT NULL   DEFAULT now(),
	"Email" varchar(255) NOT NULL,
	"Password" varchar(255) NOT NULL,
	"Role" user_role NOT NULL   DEFAULT 'user',
	"State" user_state NOT NULL   DEFAULT 'active',
	"Username" varchar(50) NOT NULL,
	"UserID" serial NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Category" ADD CONSTRAINT "PK_Category"
	PRIMARY KEY ("CategoryID")
;

CREATE INDEX "IXFK_Category_subcategories" ON "Category" ("parentCategory" ASC)
;

ALTER TABLE "Comment" ADD CONSTRAINT "PK_Comment"
	PRIMARY KEY ("CommentID")
;

CREATE INDEX "IXFK_Comment_listing" ON "Comment" (listing ASC)
;

CREATE INDEX "IXFK_Comment_replies" ON "Comment" ("parentComment" ASC)
;

ALTER TABLE "Listing" ADD CONSTRAINT "PK_Listing"
	PRIMARY KEY ("ListingID")
;

CREATE INDEX "IXFK_Listing_belongsTo" ON "Listing" ("belongsTo" ASC)
;

CREATE INDEX "IXFK_Listing_createdListings" ON "Listing" (author ASC)
;

ALTER TABLE "Message" ADD CONSTRAINT "PK_Message"
	PRIMARY KEY ("MessageID")
;

CREATE INDEX "IXFK_Message_messages" ON "Message" (ticket ASC)
;

ALTER TABLE "Notification" ADD CONSTRAINT "PK_Notification"
	PRIMARY KEY ("NotificationID")
;

CREATE INDEX "IXFK_Notification_notifications" ON "Notification" (recipient ASC)
;

ALTER TABLE "Picture" ADD CONSTRAINT "PK_Picture"
	PRIMARY KEY ("PictureID")
;

CREATE INDEX "IXFK_Picture_pictures" ON "Picture" (listing ASC)
;

ALTER TABLE "Rating" ADD CONSTRAINT "PK_Rating"
	PRIMARY KEY ("RatingID")
;

CREATE INDEX "IXFK_Rating_receivedRatings" ON "Rating" (reviewed ASC)
;

ALTER TABLE "Report" ADD CONSTRAINT "PK_Report"
	PRIMARY KEY ("ReportID")
;

CREATE INDEX "IXFK_Report_submittedReports" ON "Report" (reporter ASC)
;

ALTER TABLE "Ticket" ADD CONSTRAINT "PK_Ticket"
	PRIMARY KEY ("TicketID")
;

CREATE INDEX "IXFK_Ticket_conversations" ON "Ticket" ("subjectListing" ASC)
;

ALTER TABLE "User" ADD CONSTRAINT "PK_User"
	PRIMARY KEY ("UserID")
;

CREATE UNIQUE INDEX "UQ_User_Email" ON "User" ("Email" ASC)
;

CREATE UNIQUE INDEX "UQ_User_Username" ON "User" ("Username" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Category" ADD CONSTRAINT "FK_Category_subcategories"
	FOREIGN KEY ("parentCategory") REFERENCES "Category" ("CategoryID") ON DELETE Set Null ON UPDATE No Action
;

ALTER TABLE "Comment" ADD CONSTRAINT "FK_Comment_comments"
	FOREIGN KEY (author) REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Comment" ADD CONSTRAINT "FK_Comment_replies"
	FOREIGN KEY ("parentComment") REFERENCES "Comment" ("CommentID") ON DELETE Set Null ON UPDATE No Action
;

ALTER TABLE "Comment" ADD CONSTRAINT "FK_Comment_listing"
	FOREIGN KEY (listing) REFERENCES "Listing" ("ListingID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Listing" ADD CONSTRAINT "FK_Listing_belongsTo"
	FOREIGN KEY ("belongsTo") REFERENCES "Category" ("CategoryID") ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE "Listing" ADD CONSTRAINT "FK_Listing_createdListings"
	FOREIGN KEY (author) REFERENCES "User" ("UserID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Message" ADD CONSTRAINT "FK_Message_sentMessages"
	FOREIGN KEY (sender) REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Message" ADD CONSTRAINT "FK_Message_messages"
	FOREIGN KEY (ticket) REFERENCES "Ticket" ("TicketID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Notification" ADD CONSTRAINT "FK_Notification_notifications"
	FOREIGN KEY (recipient) REFERENCES "User" ("UserID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Notification" ADD CONSTRAINT "FK_Notification_ticketNotification"
	FOREIGN KEY (ticket) REFERENCES "Ticket" ("TicketID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Picture" ADD CONSTRAINT "FK_Picture_pictures"
	FOREIGN KEY (listing) REFERENCES "Listing" ("ListingID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Rating" ADD CONSTRAINT "FK_Rating_receivedRatings"
	FOREIGN KEY (reviewed) REFERENCES "User" ("UserID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Rating" ADD CONSTRAINT "FK_Rating_givenRatings"
	FOREIGN KEY (reviewer) REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Report" ADD CONSTRAINT "FK_Report_reportedListing"
	FOREIGN KEY ("reportedListing") REFERENCES "Listing" ("ListingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Report" ADD CONSTRAINT "FK_Report_submittedReports"
	FOREIGN KEY (reporter) REFERENCES "User" ("UserID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Report" ADD CONSTRAINT "FK_Report_reportedUser"
	FOREIGN KEY ("reportedUser") REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Ticket" ADD CONSTRAINT "FK_Ticket_conversations"
	FOREIGN KEY ("subjectListing") REFERENCES "Listing" ("ListingID") ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE "Ticket" ADD CONSTRAINT "FK_Ticket_buyer"
	FOREIGN KEY (buyer) REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 

 

 
