export const INIT = "APP_INIT";
export const ENTER_LOGIN = "ENTER_LOGIN";
export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const ENTER_REGISTER = "ENTER_REGISTER";
export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
export const LOGOUT = "LOGOUT";

export const ENTER_PROFILE = "ENTER_USER_PROFILE";

export const ENTER_LISTING_LIST = "ENTER_LISTING_LIST";
export const ENTER_LISTING_DETAIL = "ENTER_LISTING_DETAIL";
export const ENTER_LISTING_ADMINISTRATION = "ENTER_LISTING_ADMINISTRATION";
export const CREATE_LISTING = "CREATE_LISTING";
export const UPDATE_LISTING = "UPDATE_LISTING";
export const ACTIVATE_LISTING = "ACTIVATE_LISTING";
export const SELL_LISTING = "SELL_LISTING";
export const DELETE_LISTING = "DELETE_LISTING";

export const ENTER_TICKET_LIST = "ENTER_TICKET_LIST";
export const ENTER_TICKET_DETAIL = "ENTER_TICKET_DETAIL";

export const CONTACT_SELLER = "CONTACT_SELLER";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const CLOSE_TICKET = "CLOSE_TICKET";

export const SET_FILTERS = "SET_FILTERS";

export const SUBMIT_RATING = "SUBMIT_RATING";

export const SUBMIT_REPORT = "SUBMIT_REPORT";

export const BLOCK_USER = "BLOCK_USER";
export const UNBLOCK_USER = "UNBLOCK_USER";
export const BLOCK_LISTING = "BLOCK_LISTING";
export const UNBLOCK_LISTING = "UNBLOCK_LISTING";

export const ENTER_CREATE_LISTING = "ENTER_CREATE_LISTING";

export const UPLOAD_PICTURE = "UPLOAD_PICTURE";
export const DELETE_PICTURE = "DELETE_PICTURE";

export const ENTER_ADMIN = "ENTER_ADMIN";
export const DISMISS_REPORT = "DISMISS_REPORT";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const SUBMIT_COMMENT = "SUBMIT_COMMENT";

export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
